# Generated by Django 3.2.4 on 2021-07-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipapp', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
